const weatherIcons = [
  { code: 1000, dayIcon: "sunny.svg", nightIcon: "moon.svg" },
  { code: 1003, dayIcon: "PartyCloudyDay.svg", nightIcon: "PartyCloudyNight.svg" },
  { code: 1006, dayIcon: "Cloudy.svg", nightIcon: "Cloudy.svg" },
  { code: 1009, dayIcon: "OvercastDay.svg", nightIcon: "OvercastNight.svg" },
  { code: 1030, dayIcon: "Cloudy.svg", nightIcon: "Cloudy.svg" },
  { code: 1063, dayIcon: "PatchyRain.svg", nightIcon: "PatchyRain.svg" },
  { code: 1066, dayIcon: "PatchySnow.svg", nightIcon: "PatchySnow.svg" },
  { code: 1069, dayIcon: "PatchySleet.svg", nightIcon: "PatchySleet.svg" },
  { code: 1072, dayIcon: "FreezingDrizzle.svg", nightIcon: "FreezingDrizzle.svg" },
  { code: 1087, dayIcon: "Thunder.svg", nightIcon: "Thunder.svg" },
  { code: 1114, dayIcon: "PatchySnow.svg", nightIcon: "PatchySnow.svg" },
  { code: 1117, dayIcon: "Blizzard.svg", nightIcon: "Blizzard.svg" },
  { code: 1135, dayIcon: "Cloudy.svg", nightIcon: "Cloudy.svg" },
  { code: 1147, dayIcon: "FreezingFog.svg", nightIcon: "FreezingFog.svg" },
  { code: 1150, dayIcon: "FreezingDrizzle.svg", nightIcon:"FreezingDrizzle.svg"},
  { code: 1153, dayIcon: "FreezingDrizzle.svg", nightIcon: "FreezingDrizzle.svg" },
  { code: 1168, dayIcon: "FreezingDrizzle.svg", nightIcon: "FreezingDrizzle.svg" },
  { code: 1171, dayIcon: "FreezingDrizzle.svg", nightIcon: "FreezingDrizzle.svg" },
  { code: 1180, dayIcon: "rain.svg", nightIcon: "rain.svg" },
  { code: 1183, dayIcon: "ModerateRain.svg", nightIcon: "ModerateRain.svg" },
  { code: 1186, dayIcon:  "ModerateRain.svg", nightIcon:  "ModerateRain.svg" },
  { code: 1189, dayIcon:  "ModerateRain.svg", nightIcon:  "ModerateRain.svg" },
  { code: 1192, dayIcon:  "ModerateRain.svg", nightIcon:  "ModerateRain.svg" },
  { code: 1195, dayIcon:  "ModerateRain.svg", nightIcon:  "ModerateRain.svg" },
  { code: 1198, dayIcon: "PatchyRain.svg", nightIcon: "PatchyRain.svg" },
  { code: 1201, dayIcon: "ModerateRain.svg", nightIcon: "ModerateRain.svg" },
  { code: 1204, dayIcon: "PatchySleet.svg", nightIcon: "PatchySleet.svg" },
  { code: 1207, dayIcon: "PatchySleet.svg", nightIcon: "PatchySleet.svg" },
  { code: 1210, dayIcon: "PatchySnow.svg", nightIcon: "PatchySnow.svg" },
  { code: 1213, dayIcon: "PatchySnow.svg", nightIcon: "PatchySnow.svg" },
  { code: 1216, dayIcon: "PatchySnow.svg", nightIcon: "PatchySnow.svg" },
  { code: 1219, dayIcon: "PatchySnow.svg", nightIcon: "PatchySnow.svg" },
  { code: 1222, dayIcon: "Blizzard.svg", nightIcon: "Blizzard.svg" },
  { code: 1225, dayIcon: "Blizzard.svg", nightIcon: "Blizzard.svg" },
  { code: 1237, dayIcon: "Blizzard.svg", nightIcon: "Blizzard.svg" },
  { code: 1240, dayIcon: "PatchyRain.svg", nightIcon: "PatchyRain.svg" },
  { code: 1243, dayIcon: "ModerateRain.svg", nightIcon: "ModerateRain.svg" },
  { code: 1246, dayIcon: "ModerateRain.svg", nightIcon: "ModerateRain.svg" },
  { code: 1249, dayIcon: "PatchySleet.svg", nightIcon: "PatchySleet.svg" },
  { code: 1252, dayIcon: "PatchySleet.svg", nightIcon: "PatchySleet.svg" },
  { code: 1255, dayIcon: "PatchySnow.svg", nightIcon: "PatchySnow.svg" },
  { code: 1258, dayIcon: "Blizzard.svg", nightIcon: "Blizzard.svg" },
  { code: 1261, dayIcon: "Blizzard.svg", nightIcon: "Blizzard.svg" },
  { code: 1264, dayIcon: "Blizzard.svg", nightIcon: "Blizzard.svg" },
  { code: 1273, dayIcon: "RainThunder.svg", nightIcon: "RainThunder.svg" },
  { code: 1276, dayIcon: "RainThunder.svg", nightIcon: "RainThunder.svg" },
  { code: 1279, dayIcon: "SnowThunder.svg", nightIcon: "SnowThunder.svg" },
  { code: 1282, dayIcon: "SnowThunder.svg", nightIcon: "SnowThunder.svg" }
];

export default weatherIcons;
